#
#	Configuration for Auto Lift 1
#		19 July 2025, Mod 1/21/26
#
[Drivers]
##### Large Machine Setup #####

controller = LargeMachineController

auth = ADCommonAPIAuth

#rfid = KeyboardRFID
rfid = StdInRFID
log = FileLog

relay = Relay
relay_interface = PiGpioInterface

currentSense = BinaryCurrentSense
currentsense_interface = PiGpioInterface

light = RGBLight
light_interface = PiGpioInterface

[LargeMachineController]
#light_idle = blue, false, false
#light_error = red, true, 3
#rise_time =   # Time (in seconds, (default 0.3) to wait before checking current sensor state
#key =  #allows remapping of color assignments. See LargeMachineController code

#
# This is the ***inactivity timer*** any use resets it. 
#

#timeout_time = 900
timeout_time = 30

[ADCommonAPIAuth]
url = http://192.168.203.30:8083/badgeGroupMembership
group = Infrastructure Interlock Test

#[KeyboardRFID]
#device=/dev/input/by-id/usb-Sycreader_RFID_Technology_Co.__Ltd_SYC_ID_IC_USB_Reader_08FF20140315-event-kbd
#device=/dev/RFID_Reader_0

# RFID reader was aliased using a UDEV rule to a common name so that swapping readers is less likely to 
# require editing the ini file, now ussing StdInRFID instaed of KeyboardRFID

[BinaryCurrentSense]
# Threshold value to begin counting as ON
threshold = 1 
interface_position = GPIO27, inverting
#interface_position = 1  # used with PiFaceInterface

[Relay]
interface_position = GPIO17 ,  non-inverting
#interface_position = 2  # used with PiFaceInterface

[RGBLight]
interface_position_red = GPIO22, non-inverting
interface_position_green = GPIO23, non-inverting
interface_position_blue = GPIO24, non-inverting

[FileLog]
filename = KeyMaster.log
# format = 
# date_format = 
# log_level= debug|info|error
